### ISSUE TITLE
readme.md 프로젝트 아키텍쳐 이미지

### ISSUE THREAD

**Issue by daersh** [beyond-sw-camp/be04-2nd-3team-itAbility#13]
<img width="1086" alt="스크린샷 2024-03-11 오전 9 14 54" src="https://github.com/beyond-sw-camp/be04-2nd-3team-itAbility/assets/22255663/34673def-a6e0-4eb4-85b5-f121cf1f4599">

<img width="997" alt="스크린샷 2024-03-11 오전 9 17 41" src="https://github.com/beyond-sw-camp/be04-2nd-3team-itAbility/assets/22255663/04ec3f18-cdc1-4e43-ba8e-7b22b71cc6dd">

<img width="1153" alt="스크린샷 2024-03-11 오전 9 35 47" src="https://github.com/beyond-sw-camp/be04-2nd-3team-itAbility/assets/22255663/69df9a16-045d-4615-afd2-5412363a0df2">

<img width="1240" alt="스크린샷 2024-03-13 오후 3 49 16" src="https://github.com/beyond-sw-camp/be04-2nd-3team-itAbility/assets/22255663/24ff154a-ef98-4f42-8fe6-14ec479b53ba">

<img width="1116" alt="스크린샷 2024-03-13 오후 3 49 02" src="https://github.com/beyond-sw-camp/be04-2nd-3team-itAbility/assets/22255663/47ac65d0-6a9a-4d63-8f9d-f5348d48a3f0">

**Comment by goeunpark123** [comment]
아키텍쳐 사이트에서 내보내기로 이미지 파일 저장 가능해요!
