### ISSUE TITLE
모집글 등록, 조회, 삭제 기능

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-2nd-3team-itAbility#2]
## 어떤 기능인가요?

> 모집글 테이블에 새로운 모집글 데이터 추가, 모집글 테이블의 데이터 조회, 모집글 테이블의 데이터 삭제 기능 구현

## 작업 상세 내용

- [x] html 화면을 통해 입력받은 데이터를 모집글 테이블에 저장하는 기능 구현
- [x] 모집글 테이블에 저장된 데이터를 html 화면을 통해 전체 조회하는 기능 구현
- [x] html 화면을 통해 입력받은 recruitId의 모집글 데이터를 삭제하는 기능 구현

**Comment by daersh** [comment]
저장, 조회, 삭제 기능 확인 했습니다.
