### ISSUE TITLE
모집글 등록 기능 수정

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-2nd-3team-itAbility#3]
## 어떤 기능인가요?

> 모집글 등록 시에 테이블에 memberId를 저장하지 않는 오류 수정

## 작업 상세 내용

- [x] 모집글 등록 시에 저장되는 데이터에 memberId 추가

**Comment by kyulin-Kim** [comment]
오류 수정 확인했습니다 :-)
