### ISSUE TITLE
모집글 등록, 수정, 삭제, 조회 기능 개선

### ISSUE THREAD

**Issue by goeunpark123** [beyond-sw-camp/be04-2nd-3team-itAbility#7]
## 어떤 기능인가요?

> 모집글 테이블 이외의 연관 테이블에도 데이터 변경이 일어나도록 개선

## 작업 상세 내용

- [x] mybatis를 사용하여 작성한 쿼리를 통해 다른 테이블의 데이터까지 추가로 조회하는 기능 구현
- [x] 모집글 테이블 이외의 연관 테이블에 데이터가 추가되는 기능 구현
- [x] 모집글 테이블에서 삭제가 일어나면 연관 테이블의 데이터도 삭제되도록 DB 수정

**Comment by kyulin-Kim** [comment]
기능 개선 해주셔서 감사합니다, 고생하셨습니다 :-)
